export const MonitoredObjectConstants = {
  GET_PAGINATE_REQUEST: "GET_PAGINATE_REQUEST",
  GET_PAGINATE_SUCCESS: "GET_PAGINATE_SUCCESS",
  GET_PAGINATE_FAILURE: "GET_PAGINATE_FAILURE",

  GET_ALL_MONITORED_OBJECT_REQUEST: "GET_ALL_MONITORED_OBJECT_REQUEST",
  GET_ALL_MONITORED_OBJECT_SUCCESS: "GET_ALL_MONITORED_OBJECT_SUCCESS",
  GET_ALL_MONITORED_OBJECT_FAILURE: "GET_ALL_MONITORED_OBJECT_FAILURE",

  CREATE_MONITORED_REQUEST: "CREATE_MONITORED_REQUEST",
  CREATE_MONITORED_SUCCESS: "CREATE_MONITORED_SUCCESS",
  CREATE_MONITORED_FAILURE: "CREATE_MONITORED_FAILURE",

  EDIT_MONITORED_REQUEST: "EDIT_MONITORED_REQUEST",
  EDIT_MONITORED_SUCCESS: "EDIT_MONITORED_SUCCESS",
  EDIT_MONITORED_FAILURE: "EDIT_MONITORED_FAILURE",

  DELETE_MONITORED_REQUEST: "DELETE_MONITORED_REQUEST",
  DELETE_MONITORED_SUCCESS: "DELETE_MONITORED_SUCCESS",
  DELETE_MONITORED_FAILURE: "DELETE_MONITORED_FAILURE",

  NOTIFICATION_MESSAGE: "NOTIFICATION_MESSAGE",
  OBJECT_SUCCESS: "OBJECT_SUCCESS",
  OBJECT_FAILURE: "OBJECT_FAILURE",
};
