const ATTACH_PARAMS = {
  UAV_SOURCE: 'UAV_SOURCE',
  TIME: 'TIME',
  COORDINATE: 'COORDINATE',
  LOCATION: 'LOCATION',
  JOURNEYS: 'JOURNEYS',
  WEATHER: 'WEATHER',
  TEMPERATURE: 'TEMPERATURE',
  HUMIDITY: 'HUMIDITY',
};
export default ATTACH_PARAMS;
