export const CategoryConstants = {
  GET_PAGINATE_REQUEST: "GET_PAGINATE_REQUEST",
  GET_PAGINATE_SUCCESS: "GET_PAGINATE_SUCCESS",
  GET_PAGINATE_FAILURE: "GET_PAGINATE_FAILURE",

  GET_ALL_CATEGORY_REQUEST: "GET_ALL_CATEGORY_REQUEST",
  GET_ALL_CATEGORY_SUCCESS: "GET_ALL_CATEGORY_SUCCESS",
  GET_ALL_CATEGORY_FAILURE: "GET_ALL_CATEGORY_FAILURE",

  CREATE_CATEGORY_MONITORED_REQUEST: "CREATE_CATEGORY_MONITORED_REQUEST",
  CREATE_CATEGORY_MONITORED_SUCCESS: "CREATE_CATEGORY_MONITORED_SUCCESS",
  CREATE_CATEGORY_MONITORED_FAILURE: "CREATE_CATEGORY_MONITORED_FAILURE",

  EDIT_CATEGORY_MONITORED_REQUEST: "EDIT_CATEGORY_MONITORED_REQUEST",
  EDIT_CATEGORY_MONITORED_SUCCESS: "EDIT_CATEGORY_MONITORED_SUCCESS",
  EDIT_CATEGORY_MONITORED_FAILURE: "EDIT_CATEGORY_MONITORED_FAILURE",

  DELETE_MONITORED_REQUEST: "DELETE_MONITORED_REQUEST",
  DELETE_MONITORED_SUCCESS: "DELETE_MONITORED_SUCCESS",
  DELETE_MONITORED_FAILURE: "DELETE_MONITORED_FAILURE",

  NOTIFICATION_MESSAGE: "NOTIFICATION_MESSAGE",
  CAT_MONITORED_FAILURE: "CAT_MONITORED_FAILURE",
  CAT_MONITORED_SUCCESS: "CAT_MONITORED_SUCCESS",
};
