create table public."__EFMigrationsHistory"
(
    "MigrationId"    varchar(150) not null
        constraint "PK___EFMigrationsHistory"
            primary key,
    "ProductVersion" varchar(32)  not null
);

alter table public."__EFMigrationsHistory"
    owner to macbookpro;

create table public."DroneLogs"
(
    "EntityLogPrimaryKeyId" integer generated by default as identity
        constraint "PK_DroneLogs"
            primary key,
    "Timestamp"             timestamp not null,
    "EntityId"              varchar(255),
    "AuthorId"              varchar(255),
    "Type"                  integer   not null,
    "Description"           text,
    "ProjectType"           varchar(255),
    "Name"                  varchar(255),
    "Longitude"             integer   not null,
    "Latitude"              integer   not null,
    "UavConnectId"          varchar(255)
);

alter table public."DroneLogs"
    owner to macbookpro;

create table public."ImageLogs"
(
    "EntityLogPrimaryKeyId" integer generated by default as identity
        constraint "PK_ImageLogs"
            primary key,
    "Timestamp"             timestamp not null,
    "EntityId"              varchar(255),
    "AuthorId"              varchar(255),
    "Type"                  integer   not null,
    "Description"           text,
    "ProjectType"           varchar(255),
    "State"                 varchar(255),
    "Link"                  varchar(255),
    "DroneId"               varchar(255),
    "IncidentId"            varchar(255)
);

alter table public."ImageLogs"
    owner to macbookpro;

create table public."IncidentLogs"
(
    "EntityLogPrimaryKeyId" integer generated by default as identity
        constraint "PK_IncidentLogs"
            primary key,
    "Timestamp"             timestamp not null,
    "EntityId"              varchar(255),
    "AuthorId"              varchar(255),
    "Type"                  integer   not null,
    "Description"           text,
    "ProjectType"           varchar(255),
    "State"                 varchar(255),
    "RegionId"              varchar(255),
    "Name"                  varchar(255)
);

alter table public."IncidentLogs"
    owner to macbookpro;

create table public."MonitorRegionLogs"
(
    "EntityLogPrimaryKeyId" integer generated by default as identity
        constraint "PK_MonitorRegionLogs"
            primary key,
    "Timestamp"             timestamp not null,
    "EntityId"              varchar(255),
    "AuthorId"              varchar(255),
    "Type"                  integer   not null,
    "Description"           text,
    "ProjectType"           varchar(255),
    "State"                 varchar(255),
    "Name"                  varchar(255)
);

alter table public."MonitorRegionLogs"
    owner to macbookpro;

create table public."ObjectObserves"
(
    "EntityLogPrimaryKeyId" integer generated by default as identity
        constraint "PK_ObjectObserves"
            primary key,
    "Timestamp"             timestamp not null,
    "EntityId"              varchar(255),
    "AuthorId"              varchar(255),
    "Type"                  integer   not null,
    "Description"           text,
    "ProjectType"           varchar(255),
    "State"                 varchar(255),
    "Name"                  varchar(255),
    "RegionId"              varchar(255)
);

alter table public."ObjectObserves"
    owner to macbookpro;

create table public."Payloads"
(
    "EntityLogPrimaryKeyId" integer generated by default as identity
        constraint "PK_Payloads"
            primary key,
    "Timestamp"             timestamp not null,
    "EntityId"              varchar(255),
    "AuthorId"              varchar(255),
    "Type"                  integer   not null,
    "Description"           text,
    "ProjectType"           varchar(255),
    "State"                 varchar(255),
    "Name"                  varchar(255),
    "DroneId"               varchar(255)
);

alter table public."Payloads"
    owner to macbookpro;

create table public."ResolveProblemLogs"
(
    "EntityLogPrimaryKeyId" integer generated by default as identity
        constraint "PK_ResolveProblemLogs"
            primary key,
    "Timestamp"             timestamp not null,
    "EntityId"              varchar(255),
    "AuthorId"              varchar(255),
    "Type"                  integer   not null,
    "Description"           text,
    "ProjectType"           varchar(255),
    "State"                 varchar(255),
    "RegionId"              varchar(255),
    "Name"                  varchar(255)
);

alter table public."ResolveProblemLogs"
    owner to macbookpro;

create table public."StaticalLogs"
(
    "EntityLogPrimaryKeyId" integer generated by default as identity
        constraint "PK_StaticalLogs"
            primary key,
    "Timestamp"             timestamp not null,
    "EntityId"              varchar(255),
    "AuthorId"              varchar(255),
    "Type"                  integer   not null,
    "Description"           text,
    "ProjectType"           varchar(255),
    "State"                 varchar(255),
    "RegionId"              varchar(255),
    "Name"                  varchar(255)
);

alter table public."StaticalLogs"
    owner to macbookpro;

create table public."SystemLogs"
(
    "Id"          integer generated by default as identity
        constraint "PK_SystemLogs"
            primary key,
    "Timestamp"   timestamp not null,
    "Level"       integer   not null,
    "AuthorId"    varchar(255),
    "Description" text,
    "ProjectType" varchar(255),
    "WorkName"    varchar(255)
);

alter table public."SystemLogs"
    owner to macbookpro;

create table public."UavConnectLogs"
(
    "EntityLogPrimaryKeyId" integer generated by default as identity
        constraint "PK_UavConnectLogs"
            primary key,
    "Timestamp"             timestamp not null,
    "EntityId"              varchar(255),
    "AuthorId"              varchar(255),
    "Type"                  integer   not null,
    "Description"           text,
    "ProjectType"           varchar(255),
    "State"                 varchar(255),
    "Name"                  varchar(255),
    "RegionId"              varchar(255)
);

alter table public."UavConnectLogs"
    owner to macbookpro;

create table public."UserLog"
(
    "EntityLogPrimaryKeyId" integer generated by default as identity
        constraint "PK_UserLog"
            primary key,
    "Timestamp"             timestamp not null,
    "EntityId"              varchar(255),
    "AuthorId"              varchar(255),
    "Type"                  integer   not null,
    "Description"           text,
    "ProjectType"           varchar(255),
    "Metadata"              text,
    "RegionId"              varchar(255),
    "IncidentId"            varchar(255),
    "ResolveProblemId"      varchar(255),
    "Name"                  varchar(255)
);

alter table public."UserLog"
    owner to macbookpro;

create table public."VideoLogs"
(
    "EntityLogPrimaryKeyId" integer generated by default as identity
        constraint "PK_VideoLogs"
            primary key,
    "Timestamp"             timestamp not null,
    "EntityId"              varchar(255),
    "AuthorId"              varchar(255),
    "Type"                  integer   not null,
    "Description"           text,
    "ProjectType"           varchar(255),
    "State"                 varchar(255),
    "DroneId"               varchar(255),
    "Link"                  varchar(255),
    "IncidentId"            varchar(255)
);

alter table public."VideoLogs"
    owner to macbookpro;

create table public."WarningLogs"
(
    "EntityLogPrimaryKeyId" integer generated by default as identity
        constraint "PK_WarningLogs"
            primary key,
    "Timestamp"             timestamp not null,
    "EntityId"              varchar(255),
    "AuthorId"              varchar(255),
    "Type"                  integer   not null,
    "Description"           text,
    "ProjectType"           varchar(255),
    "State"                 varchar(255),
    "Name"                  varchar(255),
    "RegionId"              varchar(255)
);

alter table public."WarningLogs"
    owner to macbookpro;


