export const sidebarMenu = [
  {
    key: 'Dashboard',
    heading: 'Bảng điều khiển',
    icon: 'fa fa-home-alt',
    route: '/dashboard',
  },
  {
    key: 'Drones',
    heading: 'Điều khiển drone',
    icon: 'fas fa-drone-alt',
    route: '/drones',
    subMenu: [
      {
        key: 'DroneState',
        heading: 'Tình trạng drone',
        icon: 'fal fa-monitor-heart-rate',
        route: '/drone-state',
      },
      {
        key: 'FlySetting',
        heading: 'Thiết lập đường bay',
        icon: 'fa fa-user-chart',
        route: '/fly-setting',
      },
      {
        key: 'DroneStatistic',
        heading: 'Thống kê drone',
        icon: 'fa fa-file-chart-line',
        route: '/drone-statistic',
      },
    ],
  },
  {
    key: 'FlightHub',
    heading: 'Flight hub',
    icon: 'fab fa-hubspot',
    route: '/flight-hub',
  },
  {
    key: 'Payloads',
    heading: 'Payloads',
    icon: 'fas fa-layer-group',
    route: '/payloads',
  },
  {
    key: 'metadata',
    heading: 'Hình ảnh và video',
    icon: 'fas fa-images',
    route: '/metadata',
  },
  {
    key: 'Problems',
    heading: 'Sự cố',
    icon: 'fas fa-times-octagon',
    route: '/problems',
  },
  {
    key: 'SupervisedObject',
    heading: 'Đối tượng giám sát',
    icon: 'fas fa-binoculars',
    route: '/supervised-object',
  },
  {
    key: 'GeneralStatistic',
    heading: 'Thống kê',
    icon: 'fas fa-chart-line',
    route: '/statistic',
    subMenu: [
      {
        key: 'DashboardStatistic',
        heading: 'Dashboard',
        icon: 'fas fa-chart-line',
        route: '/dashboard-statistic',
      },
      {
        key: 'DroneStatistic',
        heading: 'Drone',
        icon: 'fas fa-drone-alt',
        route: '/drone-statistic',
      },
      {
        key: 'PayloadStatistic',
        heading: 'Payload',
        icon: 'fas fa-layer-group',
        route: '/payload-statistic',
      },
      {
        key: 'ProblemStatistic',
        heading: 'Sự cố',
        icon: 'fas fa-layer-group',
        route: '/trouble-statistic',
      },
      {
        key: 'UserStatistic',
        heading: 'Người dùng',
        icon: 'fas fa-times-octagon',
        route: '/user-statistic',
      },
    ],
  },
  {
    key: 'GeneralReport',
    heading: 'Báo cáo',
    icon: 'fas fa-book',
    route: '/report',
    subMenu: [
      {
        key: 'CreateReport',
        heading: 'Tạo báo cáo',
        icon: 'fas fa-drone-alt',
        route: '/create-report',
      },
      {
        key: 'ViewReport',
        heading: 'Xem báo cáo',
        icon: 'fas fa-drone-alt',
        route: '/view-report',
      },
      {
        key: 'ManageReportTemplate',
        heading: 'Quản lý mẫu báo cáo',
        icon: 'fas fa-drone-alt',
        route: '/manage-report-template',
      },
    ],
  },
  {
    key: 'Warning',
    heading: 'Cảnh báo',
    icon: 'far fa-bell',
    route: '/warning',
  },
  {
    key: 'ActivityLog',
    heading: 'Lịch sử hoạt động',
    icon: 'fas fa-file-signature',
    route: '/activity-log',
  },
  {
    key: 'SurveillanceDomain',
    heading: 'Miền giám sát',
    icon: 'fas fa-crop-alt',
    route: '/surveillance-domain',
  },
  {
    key: 'HandleProblem',
    heading: 'Xử lý sự cố',
    icon: 'fas fa-toolbox',
    route: '/handle-problem',
  },
  {
    key: 'UserManagement',
    heading: 'Quản lý người dùng',
    icon: 'fas fa-user-circle',
    route: '/user-management',
  },
];
