/*
    This file was automatically generated by Studio 3T.

    Collection:  (luandz@it4483.cf:27017) > luoi_dien > incident_tags

    Warnings about type conversion issues are stored as comments above the
    corresponding INSERT statement of each document.
*/


SET NAMES 'utf8' COLLATE 'utf8_general_ci';

DROP TABLE IF EXISTS `incident_tags`;
CREATE TABLE `incident_tags` (
    `_id` VARBINARY(12) NOT NULL,
    `name` LONGTEXT,
    `type` VARBINARY(12),
    `__v` INTEGER,
    `createdAt` DATETIME,
    `updatedAt` DATETIME,
    PRIMARY KEY (`_id`)
) CHARSET=utf8mb4;

INSERT INTO `incident_tags` (`_id`, `name`, `type`, `__v`, `createdAt`, `updatedAt`)
    VALUES
        (x'5FC61D211770BE08D04FCAA3', 'Open', x'5FB9DA20A6183A3210F82EC7', 0, '2020-12-01 10:38:25.169000', '2020-12-01 10:59:21.305000');
INSERT INTO `incident_tags` (`_id`, `name`, `type`, `__v`, `createdAt`, `updatedAt`)
    VALUES
        (x'5FC65DCCEB49C225A4B3F014', 'cháy nhà', NULL, 0, '2020-12-01 15:14:20.400000', '2020-12-01 15:14:20.400000');
INSERT INTO `incident_tags` (`_id`, `name`, `type`, `__v`, `createdAt`, `updatedAt`)
    VALUES
        (x'5FC65DCCEB49C225A4B3F015', 'cháy cây', NULL, 0, '2020-12-01 15:14:20.401000', '2020-12-01 15:14:20.401000');
INSERT INTO `incident_tags` (`_id`, `name`, `type`, `__v`, `createdAt`, `updatedAt`)
    VALUES
        (x'5FC65E0EF76B18048C5BD7A1', 'cháy nhà', NULL, 0, '2020-12-01 15:15:26.457000', '2020-12-01 15:15:26.457000');
INSERT INTO `incident_tags` (`_id`, `name`, `type`, `__v`, `createdAt`, `updatedAt`)
    VALUES
        (x'5FC65E0EF76B18048C5BD7A2', 'cháy cây', NULL, 0, '2020-12-01 15:15:26.457000', '2020-12-01 15:15:26.457000');
INSERT INTO `incident_tags` (`_id`, `name`, `type`, `__v`, `createdAt`, `updatedAt`)
    VALUES
        (x'5FC65E6BAEA54C237C5100BA', 'cháy nhà', x'5FB9DA20A6183A3210F82EC7', 0, '2020-12-01 15:16:59.522000', '2020-12-01 15:16:59.522000');
INSERT INTO `incident_tags` (`_id`, `name`, `type`, `__v`, `createdAt`, `updatedAt`)
    VALUES
        (x'5FC65E6BAEA54C237C5100BB', 'cháy cây', x'5FB9DA20A6183A3210F82EC7', 0, '2020-12-01 15:16:59.522000', '2020-12-01 15:16:59.522000');
INSERT INTO `incident_tags` (`_id`, `name`, `type`, `__v`, `createdAt`, `updatedAt`)
    VALUES
        (x'5FC6620FA3801300E827513C', 'cháy cửa', NULL, 0, '2020-12-01 15:32:31.278000', '2020-12-01 15:32:31.278000');
INSERT INTO `incident_tags` (`_id`, `name`, `type`, `__v`, `createdAt`, `updatedAt`)
    VALUES
        (x'5FC67F68C71FF741A085A843', 'Cháy nhà rất to', x'5FB9DA20A6183A3210F82EC7', 0, '2020-12-01 17:37:44.660000', '2020-12-01 17:37:44.660000');
INSERT INTO `incident_tags` (`_id`, `name`, `type`, `__v`, `createdAt`, `updatedAt`)
    VALUES
        (x'5FC6E4ACF0CBF240FCCBE591', 'dây điện đứt', x'5FB9DA20A6183A3210F82EC7', 0, '2020-12-02 00:49:48.135000', '2020-12-02 00:49:48.135000');
INSERT INTO `incident_tags` (`_id`, `name`, `type`, `__v`, `createdAt`, `updatedAt`)
    VALUES
        (x'5FC6E4ACF0CBF240FCCBE592', 'lưới điện', x'5FB9DA20A6183A3210F82EC7', 0, '2020-12-02 00:49:48.136000', '2020-12-02 00:49:48.136000');
INSERT INTO `incident_tags` (`_id`, `name`, `type`, `__v`, `createdAt`, `updatedAt`)
    VALUES
        (x'5FC6E76D14172441A42B2847', 'Hở dây điện', x'5FB9DA20A6183A3210F82EC7', 0, '2020-12-02 01:01:33.556000', '2020-12-02 01:01:33.556000');
INSERT INTO `incident_tags` (`_id`, `name`, `type`, `__v`, `createdAt`, `updatedAt`)
    VALUES
        (x'5FC725AB049ABB0DAC360532', 'cháy cột điện', NULL, 0, '2020-12-02 05:27:07.831000', '2020-12-02 05:27:07.831000');
INSERT INTO `incident_tags` (`_id`, `name`, `type`, `__v`, `createdAt`, `updatedAt`)
    VALUES
        (x'5FCFBAF644B23257F3B4308B', 'cháy chung cư', x'5FB9DA20A6183A3210F82EC7', 0, '2020-12-08 17:42:14.501000', '2020-12-08 17:42:14.501000');
INSERT INTO `incident_tags` (`_id`, `name`, `type`, `__v`, `createdAt`, `updatedAt`)
    VALUES
        (x'5FD8D09775720623E4CADC95', 'cháy cây', x'5FB9DA20A6183A3210F82EC6', 0, '2020-12-15 15:04:55.669000', '2020-12-15 15:04:55.669000');
INSERT INTO `incident_tags` (`_id`, `name`, `type`, `__v`, `createdAt`, `updatedAt`)
    VALUES
        (x'5FE19B23EC731F9F9E0FF2FF', 'đổ cột điện', x'5FB9DA20A6183A3210F82EC7', 0, '2020-12-22 07:07:15.845000', '2020-12-22 07:07:15.845000');
INSERT INTO `incident_tags` (`_id`, `name`, `type`, `__v`, `createdAt`, `updatedAt`)
    VALUES
        (x'5FE1A03AEC731F9F9E0FF310', 'mắc cột điện', x'5FB9DA20A6183A3210F82EC7', 0, '2020-12-22 07:28:58.161000', '2020-12-22 07:28:58.161000');
INSERT INTO `incident_tags` (`_id`, `name`, `type`, `__v`, `createdAt`, `updatedAt`)
    VALUES
        (x'5FE1AFA3947D1CA19BCE8223', 'vo de', x'5FB9DA20A6183A3210F82EC4', 0, '2020-12-22 08:34:43.342000', '2020-12-22 08:34:43.342000');
INSERT INTO `incident_tags` (`_id`, `name`, `type`, `__v`, `createdAt`, `updatedAt`)
    VALUES
        (x'5FE1B3F0947D1CA19BCE822C', 'rac thai', x'5FB9DA20A6183A3210F82EC4', 0, '2020-12-22 08:53:04.708000', '2020-12-22 08:53:04.708000');
INSERT INTO `incident_tags` (`_id`, `name`, `type`, `__v`, `createdAt`, `updatedAt`)
    VALUES
        (x'5FE1B482AF3D667C5A4B135A', 'chim ngã ', x'5FB9DA20A6183A3210F82EC7', 0, '2020-12-22 08:55:30.848000', '2020-12-22 08:55:30.848000');
INSERT INTO `incident_tags` (`_id`, `name`, `type`, `__v`, `createdAt`, `updatedAt`)
    VALUES
        (x'5FE1B482AF3D667C5A4B135B', 'Vỡ đê', x'5FB9DA20A6183A3210F82EC7', 0, '2020-12-22 08:55:30.849000', '2020-12-22 08:55:30.849000');
INSERT INTO `incident_tags` (`_id`, `name`, `type`, `__v`, `createdAt`, `updatedAt`)
    VALUES
        (x'5FE1B4C2947D1CA19BCE822F', 'hong de', x'5FB9DA20A6183A3210F82EC4', 0, '2020-12-22 08:56:34.943000', '2020-12-22 08:56:34.943000');
INSERT INTO `incident_tags` (`_id`, `name`, `type`, `__v`, `createdAt`, `updatedAt`)
    VALUES
        (x'5FE1BD33947D1CA19BCE8244', 'cong thoat nuoc', x'5FB9DA20A6183A3210F82EC4', 0, '2020-12-22 09:32:35.853000', '2020-12-22 09:32:35.853000');
INSERT INTO `incident_tags` (`_id`, `name`, `type`, `__v`, `createdAt`, `updatedAt`)
    VALUES
        (x'5FE1C1205019C64BBFEF2D71', 'nut', x'5FB9DA20A6183A3210F82EC4', 0, '2020-12-22 09:49:20.026000', '2020-12-22 09:49:20.026000');
INSERT INTO `incident_tags` (`_id`, `name`, `type`, `__v`, `createdAt`, `updatedAt`)
    VALUES
        (x'5FE1C1EC5019C64BBFEF2D74', 'cay do', x'5FB9DA20A6183A3210F82EC5', 0, '2020-12-22 09:52:44.341000', '2020-12-22 09:52:44.341000');
INSERT INTO `incident_tags` (`_id`, `name`, `type`, `__v`, `createdAt`, `updatedAt`)
    VALUES
        (x'5FE1CCB25019C64BBFEF2D77', 'cot dien do', x'5FB9DA20A6183A3210F82EC7', 0, '2020-12-22 10:38:42.134000', '2020-12-22 10:38:42.134000');
INSERT INTO `incident_tags` (`_id`, `name`, `type`, `__v`, `createdAt`, `updatedAt`)
    VALUES
        (x'5FE1D633909B3DA4A8479ABF', 'héo', x'5FB9DA20A6183A3210F82EC5', 0, '2020-12-22 11:19:15.410000', '2020-12-22 11:19:15.410000');
INSERT INTO `incident_tags` (`_id`, `name`, `type`, `__v`, `createdAt`, `updatedAt`)
    VALUES
        (x'5FE1D7B2909B3DA4A8479AC2', 'cây đổ', x'5FB9DA20A6183A3210F82EC5', 0, '2020-12-22 11:25:38.046000', '2020-12-22 11:25:38.046000');
INSERT INTO `incident_tags` (`_id`, `name`, `type`, `__v`, `createdAt`, `updatedAt`)
    VALUES
        (x'5FE20C6F909B3DA4A8479AC5', 'cây đổ', x'5FB9DA20A6183A3210F82EC7', 0, '2020-12-22 15:10:39.008000', '2020-12-22 15:10:39.008000');
