/*
    This file was automatically generated by Studio 3T.

    Collection:  (luandz@it4483.cf:27017) > luoi_dien > incident_types

    Warnings about type conversion issues are stored as comments above the
    corresponding INSERT statement of each document.
*/


SET NAMES 'utf8' COLLATE 'utf8_general_ci';

DROP TABLE IF EXISTS `incident_types`;
CREATE TABLE `incident_types` (
    `_id` VARBINARY(12) NOT NULL,
    `name` LONGTEXT,
    `type` LONGTEXT,
    `createdAt` DATETIME,
    `updatedAt` DATETIME,
    `__v` INTEGER,
    PRIMARY KEY (`_id`)
) CHARSET=utf8mb4;

INSERT INTO `incident_types` (`_id`, `name`, `type`, `createdAt`, `updatedAt`, `__v`)
    VALUES
        (x'5FB9DA20A6183A3210F82EC4', 'Sự cố đê điều', 'DE_DIEU', '2020-11-22 03:25:20.473000', '2020-11-22 03:25:20.473000', 0);
INSERT INTO `incident_types` (`_id`, `name`, `type`, `createdAt`, `updatedAt`, `__v`)
    VALUES
        (x'5FB9DA20A6183A3210F82EC5', 'Tình trạng cây trồng và phun thuốc trừ sâu', 'CAY_TRONG', '2020-11-22 03:25:20.474000', '2020-11-22 03:25:20.474000', 0);
INSERT INTO `incident_types` (`_id`, `name`, `type`, `createdAt`, `updatedAt`, `__v`)
    VALUES
        (x'5FB9DA20A6183A3210F82EC6', 'Sự cố cháy rừng', 'CHAY_RUNG', '2020-11-22 03:25:20.474000', '2020-11-22 03:25:20.474000', 0);
INSERT INTO `incident_types` (`_id`, `name`, `type`, `createdAt`, `updatedAt`, `__v`)
    VALUES
        (x'5FB9DA20A6183A3210F82EC7', 'Sự cố lưới điện cao thế', 'LUOI_DIEN', '2020-11-22 03:25:20.474000', '2020-11-22 03:25:20.474000', 0);
INSERT INTO `incident_types` (`_id`, `name`, `type`, `createdAt`, `updatedAt`, `__v`)
    VALUES
        (x'5FD035A844B23257F3B43090', 'Hỏa hoạn', 'HOA_HOAN', '2020-12-09 02:25:44.584000', '2020-12-09 02:25:44.584000', 0);
